/** Guardian-facing meetings text (invitations, replies, calendar file). */
export default {
  title: 'Meetings',
  description: (name) => `Meetings you are invited to for ${name}.`,
  loading: 'Loading meetings',
  tabs: { label: 'Meetings', upcoming: 'Upcoming', past: 'Past' },
  empty: {
    upcoming: 'No upcoming meetings',
    upcomingHint: 'When the school invites you to a meeting, it will show here.',
    past: 'No past meetings',
    pastHint: 'Meetings you were invited to will be kept here.',
  },
  back: 'All meetings',
  when: 'When',
  where: 'Where',
  online: 'Online',
  joinOnline: 'Join online meeting',
  agenda: 'Agenda',
  organiser: 'Organised by',
  organiserRole: { admin: 'School office', teacher: 'Teacher' },
  duration: (minutes) => `About ${minutes} minutes`,
  cancelled: {
    title: 'This meeting was cancelled',
    reason: (reason) => `Reason: ${reason}`,
    noReason: 'The school did not give a reason.',
  },
  rsvp: {
    title: 'Will you come?',
    willAttend: 'Will attend',
    cannotAttend: 'Cannot attend',
    yourReply: (reply) => `Your reply: ${reply}`,
    noReplyYet: 'You have not replied yet.',
    note: 'Note for the school (optional)',
    notePlaceholder: 'For example: I will come with my husband.',
    save: 'Save reply',
    saved: 'Reply saved',
    changeHint: 'You can change your reply until the meeting starts.',
    closedStarted: 'Replies closed when the meeting started.',
    closedCancelled: 'You cannot reply to a cancelled meeting.',
    quickLabel: (title) => `Reply to ${title}`,
    addNote: 'Add a note',
  },
  // Meeting state badges (config/statuses.js group "meeting" gives the icon and tone).
  state: { upcoming: 'Upcoming', past: 'Held', cancelled: 'Cancelled' },
  reply: {
    will_attend: 'Will attend',
    cannot_attend: 'Cannot attend',
    no_response: 'No reply yet',
  },
  types: {
    parent_teacher: 'Parent-teacher meeting',
    orientation: 'Orientation',
    event: 'School event',
    other: 'Meeting',
  },
  addToCalendar: 'Add to calendar',
  calendarNote: 'Downloads a calendar file with the date and time in Dhaka time.',
  youAreInvited: 'You are invited',
};
